name: build

on:
  push:
    paths-ignore:
    - 'README'
    - 'screenshots/*'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUBUNAME }}
          password: ${{ secrets.DOCKERHUBTOKEN }} 
      - 
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        env:
           DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUBUNAME }}
           DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUBPWD }}
           DOCKERHUB_REPOSITORY: tylurp/shiny-server-arm